routes/web.php
    Route::post('/changePassWord', 'UserController@changePassWord')->name('changePassWord');
    Route::post('/changeAccound', 'UserController@changeAccound')->name('changeAccound');


    Route::get('chi-tiet/{detail}', 'UserController@detail')->name('detail');
    Route::get('chi-tiet-danh-muc/{detail}', 'UserController@cate_detail')->name('cate_detail');

    Route::post('/email-newsletter-post', 'UserController@store')->name('email_newsletter.store');
    Route::get('boot/ajax/quanhuyen/{id_matp}','UserController@getAddress')->name('home.getAddress');
    Route::post('/gui-yeu-cau', 'UserController@sendRequire')->name('user.sendRequire');

    Route::get('/redirect/{social}', 'SocialAuthController@redirect');
    Route::get('/callback/{social}', 'SocialAuthController@callback');



        //Gior Hang
    Route::post('gio-hang', 'CartController@add_cart')->name('add_cart');
    Route::get('remode-cart/{id}', 'CartController@remode_cart')->name('remode_cart');
    Route::get('update_cart', 'CartController@update_cart')->name('update_cart');

    // View giỏ hàng
    Route::get('check_cart', 'CartController@check_cart')->name('check_cart');

    Route::get('buy_cart', 'CartController@buy_cart')->name('buy_cart');
    Route::post('buy_cart', 'CartController@post_buy_cart')->name('buy_cart');

    Route::get('lich-su-dat-hang', 'CartController@history_cart')->name('history_cart');


    Route::get('view-cart-{id}', 'CartController@view_cart')->name('view_cart');

});



Route::group(['prefix' => 'admin','middleware' => 'admin','namespace' => 'Admin'], function () {

        // Route::get('/list', 'MenuController@index')->name('admin.menu.list');

        Route::get('/email-newsletter', 'EmailNewsletterController@index')->name('email_newsletter.index');
        
        Route::post('/excel-email-newsletter', 'EmailNewsletterController@excel_email')->name('email_newsletter.excel_email');

        Route::post('/email-newsletter/update_status', 'EmailNewsletterController@update_status')->name('email_newsletter.update_status');
        Route::get('/email-newsletter/delete_email/{id}', 'EmailNewsletterController@delete_email')->name('email_newsletter.delete_email');

        Route::get('/menu', 'MenuController@index')->name('admin.menu.list');



        Route::get('/dashboard','AdminController@index')->name('admin.dashboard');

        Route::post('uploadImg/{type}', 'AdminController@postImages'); 
        Route::post('deleteImg', 'AdminController@deleteImg'); 

        Route::get('/box-link','BoxLinkController@index')->name('box-link.index');
        Route::post('/box-link','BoxLinkController@store')->name('box-link.store');

        Route::get('/banner','BannerController@index')->name('banner.index');
        Route::post('/banner','BannerController@store')->name('banner.store');
        Route::post('/banner-create','BannerController@create')->name('banner.create');


        Route::get('/question/{type}/{id}','QuestionController@create')->name('question.create');
        Route::put('/question/{type}/{id}','QuestionController@store')->name('question.store');
        Route::get('/question-del/{id}','QuestionController@question')->name('question.question');
        Route::post('/update-question','QuestionController@updateQuestion')->name('question.updateQuestion');



        Route::resource('/cate-event','CateEventController');
        Route::resource('/event','EventController');
        Route::post('/event/update_status', 'EventController@update_status')->name('event.update_status');
        Route::get('/ajax/quanhuyen/{id_matp}','EventController@get_quan_huyen')->name('get_quan_huyen');

        Route::resource('/news','NewsController');

        Route::resource('/account','AccountController');

        Route::resource('/cate-bustle','CateBustleController');
        Route::resource('/bustle','BustleController');
        Route::post('/bustle/update_status', 'BustleController@update_status')->name('bustle.update_status');









        Route::resource('/cate-service','CateServiceController');
        Route::resource('/service','ServiceController');
        Route::post('/service/update_status', 'ServiceController@update_status')->name('service.update_status');
        Route::get('/type-service/{id}','ServiceController@typeService')->name('service.typeService');
        Route::post('/update-type-service','ServiceController@updateTypeService')->name('service.updateTypeService');
        Route::get('/delete-old-img/{id}','ServiceController@deleteImage')->name('service.deleteImage');




        Route::resource('/cate-course','CateCourseController');
        Route::resource('/course','CourseController');
        Route::post('/course/update_status', 'CourseController@update_status')->name('course.update_status');
        Route::get('/type-course/{id}','CourseController@typeCourse')->name('course.typeCourse');
        Route::post('/update-type-course','CourseController@updateTypeCourse')->name('course.updateTypeCourse');
        Route::get('/delete-old-img1/{id}','CourseController@deleteImage')->name('course.deleteImage');



        Route::get('/yeu-cau-khach-hang/khoa-hoc','SendRequireController@indexKh')->name('admin.send.indexKh');
        Route::get('/yeu-cau-khach-hang/dich-vu','SendRequireController@indexDv')->name('admin.send.indexDv');
        Route::get('/yeu-cau-khach-hang/khoa-hoc/chi-tiet/{id}','SendRequireController@index_detailKh')->name('admin.send.index_detailKh');
        Route::get('/yeu-cau-khach-hang/dich-vu/chi-tiet/{id}','SendRequireController@index_detailDv')->name('admin.send.index_detailDv');
        Route::post('/send/update_status', 'SendRequireController@update_status')->name('send.update_status');
        Route::post('/send/destroy/{id}', 'SendRequireController@destroy')->name('send.destroy');



        // START: TRAN MINH TAN
        Route::get('/product/list','ProductStoreController@index')->name('listProduct');
        Route::get('/product/add','ProductStoreController@create')->name('addProduct');
        Route::post('/product/add','ProductStoreController@store')->name('postProduct');
        Route::get('/product/edit','ProductStoreController@edit')->name('editProduct');
        Route::put('/product/edit','ProductStoreController@update')->name('updateProduct');
        Route::get('/product/delete/{id}','ProductStoreController@destroy')->name('deleteProduct');
        Route::post('/update_status', 'ProductStoreController@update_status')->name('update_status_product');
        //END: TRAN MINH TAN
        
        Route::resource('/cate-store','CateStoreController');
        // Route::resource('/product-store','ProductStoreController');
      
        // Route::get('/product/ajax/quanhuyen/{id_matp}','ProductStoreController@get_quan_huyen')->name('get_quan_huyen');
});

Route::group(['middleware' => config('menu.middleware')], function () {
    //Route::get('wmenuindex', array('uses'=>'\Harimayco\Menu\Controllers\MenuController@wmenuindex'));
    $path = rtrim(config('menu.route_path'));
    Route::post($path . '/addcustommenu', array('as' => 'haddcustommenu', 'uses' => '\Harimayco\Menu\Controllers\MenuController@addcustommenu'));
    Route::post($path . '/deleteitemmenu', array('as' => 'hdeleteitemmenu', 'uses' => '\Harimayco\Menu\Controllers\MenuController@deleteitemmenu'));
    Route::post($path . '/deletemenug', array('as' => 'hdeletemenug', 'uses' => '\Harimayco\Menu\Controllers\MenuController@deletemenug'));
    Route::post($path . '/createnewmenu', array('as' => 'hcreatenewmenu', 'uses' => '\Harimayco\Menu\Controllers\MenuController@createnewmenu'));
    Route::post($path . '/generatemenucontrol', array('as' => 'hgeneratemenucontrol', 'uses' => '\Harimayco\Menu\Controllers\MenuController@generatemenucontrol'));
    Route::post($path . '/updateitem', array('as' => 'hupdateitem', 'uses' => '\Harimayco\Menu\Controllers\MenuController@updateitem'));
});
Route::group(['prefix' => 'partner','middleware' => 'auth','namespace' => 'Admin_v2'], function () {
// 'middleware' => ['cannot:super-user']
        Route::get('/dashboard','AdminController@index')->name('partner.dashboard');
        

        // Route::get('/profiles/getSuggestCities','ProductStoreController@getSuggestCities')->name('partner.getSuggestCities');


        
        
        
        
        // Quyền đăng bán sản phẩm 
       Route::group(['middleware' => ['can:product']], function () {
            // Route::resource('/cate-store','CateStoreController');
            Route::resource('/product-store','ProductStoreController');
            Route::post('/update_status', 'ProductStoreController@update_status')->name('product-store.update_status');
        });
            Route::get('/product/ajax/quanhuyen/{id_matp}','ProductStoreController@get_quan_huyen')->name('get_quan_huyen');


            
        // Quyền khóa học
        Route::group(['middleware' => ['can:course']], function () {

            Route::get('/course-partner','CoursePartnerController@index')->name('course-partner.index');
            Route::get('/course-partner-user','CoursePartnerController@index_user')->name('course-partner.index_user');
            Route::post('/course-partner','CoursePartnerController@store')->name('course-partner.store');

            Route::get('/course-partner/{course_id}/edit','CoursePartnerController@edit')->name('course-partner.edit');
            Route::post('/course-partner/{course_id}','CoursePartnerController@update')->name('course-partner.update');
            Route::post('/course-partner-destroy/{course_id}','CoursePartnerController@destroy')->name('course-partner.destroy');
            Route::post('/course-partner-user/update_status', 'CoursePartnerController@update_status')->name('course-partner.update_status');

        });
            // Route::get('/course/ajax/quanhuyen/{id_matp}','CourseController@get_quan_huyen')->name('course.get_quan_huyen');

        // Quyền dịch vụ

app/CateEvent.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CateEvent extends Model
{
    //
}

app/Http/Controllers/Admin/CateEventController.php
<?php

namespace App\Http\Controllers\Admin;

use App\CateEvent;
use Auth;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class CateEventController extends Controller
{
    public function __construct()
    {
        $this->middleware('admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cateEvent = CateEvent::all();
        $cateEvent0 = CateEvent::where('parents', 0)->get();
        $cateEvent1 = CateEvent::where('parents', '<>', 0)->get();
        return view('admin.cateEvent.index', compact('cateEvent', 'cateEvent0', 'cateEvent1'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name'    => 'required|max:225',
            'slug'    => 'required|max:225',
            'parents' => 'required',
        ]);

        if ($validator->fails()) {
            return redirect()
                ->back()
                ->withErrors($validator)
                ->withInput($request->all());
        }
        $slug = '';
        if (CateEvent::where('slug', $request->slug)->value('slug') == null) {
            $slug = 'su-kien/' . $request->slug . '.' . 'html';
        } else {
            $slug = 'su-kien/' . $request->slug . '-' . str_random(1) . '.' . 'html';
        }

        $inserts          = new CateEvent();
        $inserts->name    = $request->name;
        $inserts->parents = 0;
        $inserts->slug    = $slug;
        try {
            $inserts->save();
            return redirect()->back()->with(['success' => 'Thêm danh mục thành công !']);
        } catch (Exception $message) {
            return redirect()->back()->with(['error' => $message->getMessage()]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\CateEvent  $cateEvent
     * @return \Illuminate\Http\Response
     */
    public function show(CateEvent $cateEvent)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\CateEvent  $cateEvent
     * @return \Illuminate\CateEvent\Response
     */
    public function edit(CateEvent $cateEvent)
    {
        $cateEventAll = CateEvent::all();;
        return view('admin.cateEvent.edit', compact('cateEvent', 'cateEventAll'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\CateEvent  $cateEvent
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, CateEvent $cateEvent)
    {

        $validator = Validator::make($request->all(), [
            'name'    => 'required|max:225',
            'slug'    => 'required|max:225',
            'parents' => 'required',
        ]);

        if ($validator->fails()) {
            return redirect()
                ->back()
                ->withErrors($validator)
                ->withInput($request->all());
        }

        $slug = '';
        if (CateEvent::where('slug', $request->slug)->whereNotIn('slug', [$request->slug])->value('slug') == null) {
            $slug = 'su-kien/' . $request->slug . '.' . 'html';
        } else {
            $slug = 'su-kien/' . $request->slug . '-' . str_random(1) . '.' . 'html';
        }
        $cateEvent->name    = $request->name;
        $cateEvent->parents = 0;
        $cateEvent->slug    = $slug;
        try {
            $cateEvent->save();
            return redirect('admin/cate-event')->with(['success' => 'Sửa danh mục thành công !']);
        } catch (Exception $message) {
            return redirect()->back()->with(['error' => $message->getMessage()]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\CateEvent  $cateEvent
     * @return \Illuminate\Http\Response
     */
    public function destroy(CateEvent $cateEvent)
    {
        $cateEvent->delete();
        return redirect()->back()->with(['success' => 'Xóa danh mục thành công !']);
    }
}

resources/views/admin/cateEvent/edit.blade.php
@extends('admin.layout.master')
@section('style.css')
    {{----}}
@endsection
@section('content')
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Chỉnh sửa danh mục</h2>
        <ol class="breadcrumb">
        <li>
            <a href="{{ route('admin.dashboard') }}">Trang chủ</a>
        </li>
        <li class="active">
            <strong>Chỉnh sửa danh mục</strong>
        </li>
    </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content">

    <div class="row">
        <div class="col-lg-12">
             @if (session('success'))
                <div class="alert alert-success pull-right alert-dismissable margin5" style="width: 50%; text-align: center">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    {{ session('success') }}
                </div>
            @endif
            @if (session('error'))
                <div class="alert alert-danger pull-right alert-dismissable margin5" style="width: 50%; text-align: center">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    {{ session('error') }}
                </div>
            @endif
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h4>Sửa danh mục</h4>
                            <div class="ibox-tools">                                          
                            </div>
                        </div>
                        <div class="ibox-content" style="padding: 50px">
                            <div class="row">
                                <form class="form-horizontal" action="{{route('cate-event.update', $cateEvent->id)}}" method="POST" enctype="multipart/form-data">
                                <input type="hidden" name="_method" value="PUT">
                                    <div class="col-lg-12">
                                        <input type="hidden" name="_token" value="{{csrf_token()}}">
                                        <div class="form-group">
                                            <label>Tên danh mục(*):</label> 
                                            <input type="text" id="name" class="form-control" name="name" placeholder="Tên tab danh mục tiếng việt" value="{{ $cateEvent->name }}" style="margin-bottom: 5px">
                                            @if($errors->has('name'))
                                                <span class="text-center text-danger" role="alert">
                                                    {{$errors->first('name')}}
                                                </span>
                                            @endif
                                            <br><span>Tên riêng sẽ hiển thị trên trang mạng của bạn</span>
                                        </div>
                                        <div class="form-group">
                                            <label>Chuỗi cho đường dẫn tĩnh</label> 
                                            
                                            @if ($cateEvent->slug)
                                                @php
                                                    $slug = explode('/', $cateEvent->slug);
                                                    $slug_1 = explode('.', $slug[1]);
                                                @endphp
                                            @endif

                                            <div class="input-group">
                                                <span class="input-group-addon">{{$slug[0]}}/</span>
                                                <input type="text" class="form-control" name="slug" id="slug" placeholder="Đường dẫn tĩnh" value="{{ $slug_1[0] }}">
                                                <span class="input-group-addon">.{{$slug_1[1]}}</span>
                                            </div>
                                             @if($errors->has('slug'))
                                                <span class="text-center text-danger" role="alert">
                                                    {{$errors->first('slug')}}
                                                </span>
                                            @endif
                                            <span>Chuỗi cho đường dẫn tĩnh là phiên bản của tên hợp chuẩn với Đường dẫn (URL). Chuỗi này bao gồm chữ cái thường, số và dấu gạch ngang (-).</span>
                                        </div>
                                    </div>
                                    <div>
                                        <a class="btn btn-sm btn-danger m-t-n-xs" href="{{ route('cate-event.index') }}"><strong>Hủy bỏ</strong></a>
                                        <button class="btn btn-sm btn-primary pull-right m-t-n-xs" type="submit"><strong>Sửa danh mục</strong></button>
                                </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection


@section('javascript')
@endsection