routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;
Route::get('/clear-cache', function() {
    Artisan::call('config:cache');
    Artisan::call('cache:clear');
    /*Artisan::call('cache:table');*/
    /*Artisan::call('migrate');*/
    Cache::flush();
    var_dump('config cache successed');
});
    Route::get('/check', 'UserController@check')->name('check');

    Route::get('/login-admin', 'Admin\LoginController@getLogin')->name('admin.login');
    Route::post('/login-admin', 'Admin\LoginController@postLogin')->name('admin.post.login');
    Route::get('/dang-xuat.html', 'Admin\LoginController@getLogout')->name('admin.logout');

    Auth::routes();

Route::group(['middleware' => 'check'], function () {

    Route::get('/', 'UserController@index')->name('home');
    Route::get('/bo-loc.html', 'UserController@filter')->name('filter');
    Route::get('/thong-tin-khoa-hoc.html', 'UserController@profileCourse')->name('profileCourse');
    Route::get('/thong-tin-dich-vu.html', 'UserController@profileService')->name('profileService');
    Route::get('/thong-tin-tai-khoan.html', 'UserController@infoAccount')->name('infoAccount');
    Route::post('/change_pass', 'UserController@changePass')->name('changePass');
    Route::post('/changePassWord', 'UserController@changePassWord')->name('changePassWord');
    Route::post('/changeAccound', 'UserController@changeAccound')->name('changeAccound');


    Route::get('chi-tiet/{detail}', 'UserController@detail')->name('detail');
    Route::get('chi-tiet-danh-muc/{detail}', 'UserController@cate_detail')->name('cate_detail');

    Route::post('/email-newsletter-post', 'UserController@store')->name('email_newsletter.store');
    Route::get('boot/ajax/quanhuyen/{id_matp}','UserController@getAddress')->name('home.getAddress');
    Route::post('/gui-yeu-cau', 'UserController@sendRequire')->name('user.sendRequire');

    Route::get('/redirect/{social}', 'SocialAuthController@redirect');
    Route::get('/callback/{social}', 'SocialAuthController@callback');



        //Gior Hang
    Route::post('gio-hang', 'CartController@add_cart')->name('add_cart');
    Route::get('remode-cart/{id}', 'CartController@remode_cart')->name('remode_cart');
    Route::get('update_cart', 'CartController@update_cart')->name('update_cart');

    // View giỏ hàng
    Route::get('check_cart', 'CartController@check_cart')->name('check_cart');

    Route::get('buy_cart', 'CartController@buy_cart')->name('buy_cart');
    Route::post('buy_cart', 'CartController@post_buy_cart')->name('buy_cart');

    Route::get('lich-su-dat-hang', 'CartController@history_cart')->name('history_cart');


    Route::get('view-cart-{id}', 'CartController@view_cart')->name('view_cart');

});



Route::group(['prefix' => 'admin','middleware' => 'admin','namespace' => 'Admin'], function () {

        // Route::get('/list', 'MenuController@index')->name('admin.menu.list');

        Route::get('/email-newsletter', 'EmailNewsletterController@index')->name('email_newsletter.index');
        
        Route::post('/excel-email-newsletter', 'EmailNewsletterController@excel_email')->name('email_newsletter.excel_email');

        Route::post('/email-newsletter/update_status', 'EmailNewsletterController@update_status')->name('email_newsletter.update_status');
        Route::get('/email-newsletter/delete_email/{id}', 'EmailNewsletterController@delete_email')->name('email_newsletter.delete_email');

        Route::get('/menu', 'MenuController@index')->name('admin.menu.list');



        Route::get('/dashboard','AdminController@index')->name('admin.dashboard');

        Route::post('uploadImg/{type}', 'AdminController@postImages'); 
        Route::post('deleteImg', 'AdminController@deleteImg'); 

        Route::get('/box-link','BoxLinkController@index')->name('box-link.index');
        Route::post('/box-link','BoxLinkController@store')->name('box-link.store');

        Route::get('/banner','BannerController@index')->name('banner.index');
        Route::post('/banner','BannerController@store')->name('banner.store');
        Route::post('/banner-create','BannerController@create')->name('banner.create');


        Route::get('/question/{type}/{id}','QuestionController@create')->name('question.create');
        Route::put('/question/{type}/{id}','QuestionController@store')->name('question.store');
        Route::get('/question-del/{id}','QuestionController@question')->name('question.question');
        Route::post('/update-question','QuestionController@updateQuestion')->name('question.updateQuestion');



        Route::resource('/cate-event','CateEventController');
        Route::resource('/event','EventController');
        Route::post('/event/update_status', 'EventController@update_status')->name('event.update_status');
        Route::get('/ajax/quanhuyen/{id_matp}','EventController@get_quan_huyen')->name('get_quan_huyen');

        Route::resource('/news','NewsController');

        Route::resource('/account','AccountController');

        Route::resource('/cate-bustle','CateBustleController');
        Route::resource('/bustle','BustleController');
        Route::post('/bustle/update_status', 'BustleController@update_status')->name('bustle.update_status');









        Route::resource('/cate-service','CateServiceController');
        Route::resource('/service','ServiceController');
        Route::post('/service/update_status', 'ServiceController@update_status')->name('service.update_status');
        Route::get('/type-service/{id}','ServiceController@typeService')->name('service.typeService');
        Route::post('/update-type-service','ServiceController@updateTypeService')->name('service.updateTypeService');
        Route::get('/delete-old-img/{id}','ServiceController@deleteImage')->name('service.deleteImage');




        Route::resource('/cate-course','CateCourseController');
        Route::resource('/course','CourseController');
        Route::post('/course/update_status', 'CourseController@update_status')->name('course.update_status');
        Route::get('/type-course/{id}','CourseController@typeCourse')->name('course.typeCourse');
        Route::post('/update-type-course','CourseController@updateTypeCourse')->name('course.updateTypeCourse');
        Route::get('/delete-old-img1/{id}','CourseController@deleteImage')->name('course.deleteImage');



        Route::get('/yeu-cau-khach-hang/khoa-hoc','SendRequireController@indexKh')->name('admin.send.indexKh');
        Route::get('/yeu-cau-khach-hang/dich-vu','SendRequireController@indexDv')->name('admin.send.indexDv');
        Route::get('/yeu-cau-khach-hang/khoa-hoc/chi-tiet/{id}','SendRequireController@index_detailKh')->name('admin.send.index_detailKh');
        Route::get('/yeu-cau-khach-hang/dich-vu/chi-tiet/{id}','SendRequireController@index_detailDv')->name('admin.send.index_detailDv');
        Route::post('/send/update_status', 'SendRequireController@update_status')->name('send.update_status');
        Route::post('/send/destroy/{id}', 'SendRequireController@destroy')->name('send.destroy');



        // START: TRAN MINH TAN
        Route::get('/product/list','ProductStoreController@index')->name('listProduct');
        Route::get('/product/add','ProductStoreController@create')->name('addProduct');
        Route::post('/product/add','ProductStoreController@store')->name('postProduct');
        Route::get('/product/edit','ProductStoreController@edit')->name('editProduct');
        Route::put('/product/edit','ProductStoreController@update')->name('updateProduct');
        Route::get('/product/delete/{id}','ProductStoreController@destroy')->name('deleteProduct');
        Route::post('/update_status', 'ProductStoreController@update_status')->name('update_status_product');
        //END: TRAN MINH TAN
        
        Route::resource('/cate-store','CateStoreController');
        // Route::resource('/product-store','ProductStoreController');
      
        // Route::get('/product/ajax/quanhuyen/{id_matp}','ProductStoreController@get_quan_huyen')->name('get_quan_huyen');
});

Route::group(['middleware' => config('menu.middleware')], function () {
    //Route::get('wmenuindex', array('uses'=>'\Harimayco\Menu\Controllers\MenuController@wmenuindex'));
    $path = rtrim(config('menu.route_path'));
    Route::post($path . '/addcustommenu', array('as' => 'haddcustommenu', 'uses' => '\Harimayco\Menu\Controllers\MenuController@addcustommenu'));
    Route::post($path . '/deleteitemmenu', array('as' => 'hdeleteitemmenu', 'uses' => '\Harimayco\Menu\Controllers\MenuController@deleteitemmenu'));
    Route::post($path . '/deletemenug', array('as' => 'hdeletemenug', 'uses' => '\Harimayco\Menu\Controllers\MenuController@deletemenug'));
    Route::post($path . '/createnewmenu', array('as' => 'hcreatenewmenu', 'uses' => '\Harimayco\Menu\Controllers\MenuController@createnewmenu'));
    Route::post($path . '/generatemenucontrol', array('as' => 'hgeneratemenucontrol', 'uses' => '\Harimayco\Menu\Controllers\MenuController@generatemenucontrol'));
    Route::post($path . '/updateitem', array('as' => 'hupdateitem', 'uses' => '\Harimayco\Menu\Controllers\MenuController@updateitem'));
});
Route::group(['prefix' => 'partner','middleware' => 'auth','namespace' => 'Admin_v2'], function () {
// 'middleware' => ['cannot:super-user']
        Route::get('/dashboard','AdminController@index')->name('partner.dashboard');
        

        // Route::get('/profiles/getSuggestCities','ProductStoreController@getSuggestCities')->name('partner.getSuggestCities');


        
        
        
        
        // Quyền đăng bán sản phẩm 

resources/views/admin/account/create.blade.php
@extends('admin.layout.master')
@section('title','Admin - Tạo tài khoản')
@section('style')

{{-- <link href="{{ url('public/admin') }}/css/plugins/bootstrap-tagsinput/bootstrap-tagsinput.css" rel="stylesheet"> --}}

{{-- <link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/css/select2.min.css" rel="stylesheet" /> --}}

    {{-- <link href="{{ url('public/admin') }}/css/plugins/dropzone/basic.css" rel="stylesheet">
    <link href="{{ url('public/admin') }}/css/plugins/dropzone/dropzone.css" rel="stylesheet">
    <link href="{{ url('public/admin') }}/css/plugins/jasny/jasny-bootstrap.min.css" rel="stylesheet">
    <link href="{{ url('public/admin') }}/css/plugins/codemirror/codemirror.css" rel="stylesheet"> --}}
    <link href="{{ url('public/admin') }}/css/plugins/iCheck/custom.css" rel="stylesheet">
    <link href="{{ url('public/admin') }}/css/plugins/steps/jquery.steps.css" rel="stylesheet">
    <style>

        .wizard > .content > .body  position: relative; }

    </style>


@endsection

@section('content')

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Tạo tài khoản đối tác</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('admin.dashboard') }}">Trang chủ</a>
                </li>
                <li>
                    <a href="{{ route('event.index') }}">Danh sách tài khoản đối tác</a>
                </li>
                <li class="active">
                    <strong>Tạo tài khoản đối tác</strong>
                </li>
            </ol>
        </div>
    </div>
    
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox">
                    <div class="ibox-title">
                        <h5>Tạo tài khoản đối tác</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">Config option 1</a>
                                </li>
                                <li><a href="#">Config option 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <h2>
                            Tạo tài khoản đối tác
                        </h2>
                        <p>
                            Admin nhập thông tin đối tác tại đây
                        </p>
                        <form id="form" action="{{ route('account.store') }}" method="post" class="wizard-big">
                            {!! csrf_field() !!}
                            <h1>Tài khoản</h1>
                            <fieldset>
                                <h2>Thông tin tài khoản</h2>
                                <div class="row">
                                    <div class="col-lg-8">
                                        <div class="form-group">
                                            <label for="email">Tên đăng nhập *</label>
                                            <input id="email" name="email" value="taikhoan@gmail.com" type="enail" class="form-control required">
                                        </div>
                                        <div class="form-group">
                                            <label for="password">Mật khẩu *</label>
                                            <input id="password" name="password" type="text" value="vifonic_secret" class="form-control required">
                                        </div>
                                    </div>
                                    <div class="col-lg-4">
                                        <div class="text-center">
                                            <div style="margin-top: 20px">
                                                <i class="fa fa-sign-in" style="font-size: 180px;color: #e5e5e5 "></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </fieldset>
                            <h1>Đối tác</h1>
                            <fieldset>
                                <h2>Thông tin đối tác</h2>
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label for="name" >Tên công ty *</label>
                                            <input id="name" name="name" type="text" value="{{old('name')}}"  class="form-control required">
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label for="phone" >Số điện thoại*</label>
                                            <input id="phone" name="phone" type="tel"  value="{{old('phone')}}" class="form-control required">
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label>Tỉnh/Thành Phố:</label>
                                            <select name="address1" id="ThanhPho" data-placeholder="Choose a Country..." class="form-control required">
                                                <option value="">Thành Phố</option>
                                                @foreach ($city as $ci)
                                                <option value="{{$ci->matp}}">{{$ci->name}}</option>
                                                @endforeach
                                           </select>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label >Quận/Huyện:</label>
                                            <select name="address" id="QuanHuyen" data-placeholder="Choose a Country..." class="form-control required">
                                                <option value="">--Chưa chọn Quận/Huyện--</option>
                                           </select>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label for="specific_address" >Địa chỉ cụ thể *</label>
                                            <input id="specific_address" name="specific_address" type="text"  value="{{old('specific_address')}}" class="form-control required">
                                        </div>
                                    </div>
                                </div>
                            </fieldset>
                            <h1>Quyền tài khoản</h1>
                            <fieldset>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">Quyền:</label>
                                    <div class="col-sm-10">
                                        <select name="role_id" class=" form-control required">
                                            <option value="">Chọn quyền cho tài khoản</option>
                                            @foreach ($role as $rl)
                                                <option value="{{$rl->id}}" {{old('role_id') == $rl->id ? 'selected' : ''}}>{{$rl->name}}</option>
                                            @endforeach
                                       </select>
                                    </div>
                                </div>
                            <div class="text-center" style="margin-top: 120px">
                            </div>
                            </fieldset>
                            <h1>Hoàn thành</h1>
                            <fieldset>
                                <h2>Xác nhận tạo tài khoản</h2>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection


@section('scripts')
    <!-- Chosen -->
    <script src="{{ url('public/admin') }}/js/plugins/chosen/chosen.jquery.js"></script>

    <!-- Select2 -->
    <script src="{{ url('public/admin') }}/js/plugins/select2/select2.full.min.js"></script>

    <!-- Jasny -->
    <script src="{{ url('public/admin') }}/js/plugins/jasny/jasny-bootstrap.min.js"></script>

    <!-- Steps -->
    <script src="{{ url('public/admin') }}/js/plugins/staps/jquery.steps.min.js"></script>

    <!-- Jquery Validate -->
    <script src="{{ url('public/admin') }}/js/plugins/validate/jquery.validate.min.js"></script>


@endsection

@section('javascript')
    <script type="text/javascript">
        $('.chosen-select').chosen({width: "100%"});
    </script>
    <script src="{{ asset('public/pulgin/ckeditor/ckeditor.js') }}"></script>
    <script>
        $(document).on("change","#ThanhPho", function(event) {
          var id_matp = $(this).val();
          $.get("{{ url('') }}/admin/ajax/quanhuyen/"+id_matp,function(data) {
            console.log(data);
            $("#QuanHuyen").html(data);
          });
        });
    </script>
    <script>
        $('.price_range').hide();
        $(document).on("change","#EventType", function(event) {
            var value = $(this).val();
            if (value == 1) {
                $('.price_range').hide('150');
            }else {
                $('.price_range').show('150');
            };
            
        });
    </script>
    <script>
        $(document).ready(function(){
            $("#wizard").steps();
            $("#form").steps({
                bodyTag: "fieldset",
                onStepChanging: function (event, currentIndex, newIndex)
                {
                    // Always allow going backward even if the current step contains invalid fields!
                    if (currentIndex > newIndex)
                    {
                        return true;
                    }

                    // Forbid suppressing "Warning" step if the user is to young
                    if (newIndex === 3 && Number($("#age").val()) < 18)
                    {
                        return false;
                    }

                    var form = $(this);

                    // Clean up if user went backward before
                    if (currentIndex < newIndex)
                    {
                        // To remove error styles
                        $(".body:eq(" + newIndex + ") label.error", form).remove();
                        $(".body:eq(" + newIndex + ") .error", form).removeClass("error");
                    }

                    // Disable validation on fields that are disabled or hidden.
                    form.validate().settings.ignore = ":disabled,:hidden";

                    // Start validation; Prevent going forward if false
                    return form.valid();
                },
                onStepChanged: function (event, currentIndex, priorIndex)
                {
                    // Suppress (skip) "Warning" step if the user is old enough.
                    if (currentIndex === 2 && Number($("#age").val()) >= 18)
                    {
                        $(this).steps("Tiếp theo");
                    }

                    // Suppress (skip) "Warning" step if the user is old enough and wants to the previous step.
                    if (currentIndex === 2 && priorIndex === 3)
                    {
                        $(this).steps("Quay lại");
                    }
                },
                onFinishing: function (event, currentIndex)
                {
                    var form = $(this);

                    // Disable validation on fields that are disabled.
                    // At this point it's recommended to do an overall check (mean ignoring only disabled fields)
                    form.validate().settings.ignore = ":disabled";

                    // Start validation; Prevent form submission if false
                    return form.valid();
                },
                onFinished: function (event, currentIndex)
                {
                    var form = $(this);

                    // Submit form input
                    form.submit();
                }
            }).validate({
                        errorPlacement: function (error, element)
                        {
                            element.before(error);
                        },
                        rules: {
                            confirm: {
                                equalTo: "#password"
                            }
                        }
                    });
       });
    </script>
@endsection

resources/views/admin/account/index.blade.php
@extends('admin.layout.master')

@section('title','Admin - Danh sách tài khoản')
@section('content')

    
        <div class="row wrapper border-bottom white-bg page-heading">
            <div class="col-lg-10">
                <h2>Danh sách tài khoản</h2>
                <ol class="breadcrumb">
                    <li>
                        <a href="{{ route('admin.dashboard') }}">Trang chủ</a>
                    </li>
                    <li class="active">
                        <strong>Danh sách tài khoản</strong>
                    </li>
                </ol>
            </div>
            <div class="col-lg-2">

            </div>
        </div>

        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="mail-box-header">
                            <h2>
                                TÀI KHOẢN ({{$account->count()}})
                            </h2>
                            <div class="mail-tools tooltip-demo m-t-md">
                                <form action="">
                                    <div class="input-group"><input type="text" name="name_search" value="" placeholder="Tìm kiếm theo tên tài khoản !" class="input-sm form-control"> <span class="input-group-btn">
                                            <button type="submit" class="btn btn-sm btn-primary"> SEARCH !</button> </span></div>
                                </form>
                            </div>
                        </div>
                        <div class="ibox-content">
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th class="col-md-2">Tên đối tác</th>
                                            <th class="col-md-2">Email</th>
                                            <th class="col-md-2">Số điện thoại</th>
                                            <th class="col-md-2">Địa chỉ</th>
                                            <th class="col-md-2">Quyền</th>
                                            <th class="col-md-1">Coppy</th>
                                            <th class="col-md-1">Edit</th>
                                            <th class="col-md-1">DEL</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($account as $acc)
                                            <tr class="load_status_149">
                                                <td>
                                                    {{$acc->name}}
                                                </td>
                                                <td>
                                                    <span class="tag-post-danhmuc">
                                                        {{$acc->email}}
                                                    </span>
                                                </td>
                                                <td>
                                                    <span class="tag-post-danhmuc">
                                                        {{$acc->phone}}
                                                    </span>
                                                </td>
                                                <td>
                                                    <span class="tag-post-danhmuc">
                                                        {{$acc->specific_address}}
                                                    </span>
                                                </td>
                                                <td>
                                                    <span class="tag-post-danhmuc">
                                                        {{$acc->role->name}}
                                                    </span>
                                                </td>
                                                <td>
                                                    <a class="btn btn-white btn-xs">Coppy</a>
                                                </td>
                                                <td>
                                                    <a href="{{ route('event.edit',['id'=>$acc->id]) }}" class="btn-white btn btn-xs" >Edit</a>
                                                </td>
                                                <td class="text-right">
                                                    <form action="{{ route('event.destroy',['id'=>$acc->id]) }}" method="POST" style="margin-bottom: 0">
                                                        <div class="btn-group">
                                                            {{ csrf_field() }}
                                                            <input type="hidden" name="_method" value="DELETE">
                                                            <button type="submit" class="btn-white btn btn-xs">Delete</button>
                                                            
                                                        </div>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>        
@endsection
@section('javascript')
    <script>
        var _token = $('input[name="_token"]').val();
        $(document).on('click', '.colum_status', function(){
            var status = $(this).data("stt");
            var id = $(this).data("id");
             
            if(id != '')
            {
                $.ajax({
                    url:"{{ route('event.update_status') }}",
                    method:"POST",
                    data:{status:status, id:id, _token:_token},
                    success:function(data)
                    {
                        $('.load_status_'+id).load(location.href + ' .load_status_'+id+'>*')
                    }
                })
            }
            else
            {
                $('#message').html("<div class='alert alert-danger'>Enter some value</div>");
            }
        });
        
    </script>
@endsection